version: '3.8'
services:
  frontend:
    build:
      context: ./MarvelillosoAngular
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: marvelilloso
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  dbdata:
